
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lncxwvrcsuhphxxsvjod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuY3h3dnJjc3VocGh4eHN2am9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NjM4MzgsImV4cCI6MjA2NDAzOTgzOH0.82qRAvif76C7GwmFgbCvM9OZVmf-P3FLJFzXkF88_tc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    flowType: 'pkce',
    debug: process.env.NODE_ENV === 'development'
  },
  global: {
  headers: {
    'x-client-info': 'supabase-js-web'
  }
},
  db: {
    schema: 'public'
  },
  realtime: {
    params: {
      eventsPerSecond: 2
    }
  }
});

// Add error handling for auth events
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'TOKEN_REFRESHED') {
    console.log('Token refreshed at:', new Date().toISOString());
  } else if (event === 'SIGNED_OUT') {
    console.log('User signed out at:', new Date().toISOString());
    // Clear any cached data
    if (typeof window !== 'undefined') {
      localStorage.removeItem('supabase.auth.token');
    }
  }
});
